apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: fernway-backend
    newName: <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/fernway-backend
    newTag: prod-placeholder
  - name: fernway-frontend
    newName: <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/fernway-frontend
    newTag: prod-placeholder

patches:
  - path: replica-patch.yaml
  - path: hpa-patch.yaml
