apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: fernway-backend
    newName: 064589995443.dkr.ecr.eu-west-1.amazonaws.com/fernway-backend
    newTag: staging-placeholder
  - name: fernway-frontend
    newName: 064589995443.dkr.ecr.eu-west-1.amazonaws.com/fernway-frontend
    newTag: staging-placeholder

patches:
  - path: replica-patch.yaml
